Algoritmo "semnome"

Var

 a, b, c : inteiro
 resultado : inteiro

 funcao quadradoabc(x : inteiro ; y : inteiro ; z : inteiro) : inteiro
  var
  s: inteiro

  inicio

   s <- xx + yy + z*z
   retorne s

  fimfuncao

Inicio

   escreval ("digite uma valor")
   leia (a)
   escreval ("digite outro numero")
   leia (b)
   escreval ("digite o ultimo numero")
   leia (c)
   resultado <- quadradoabc(a,b,c)
   escreval ("a soma dos quadrados dos numeros", resultado)



Fimalgoritmo